name: "Sync to Azure DevOps"
description: "Automatically create/update an Azure DevOps project & repo, then sync a GitHub repo to it."
author: "GuyMicciche"
branding:
  icon: "git-merge"
  color: "blue"

inputs:
  organization:
    description: "Azure DevOps URL & organization name (e.g., dev.azure.com/myorg or myorg.visualstudio.com)"
    required: true
  pat:
    description: "Azure DevOps Personal Access Token with Build (Read & Execute), Code (Read/Write/Manage), and Project/Team (Read/Write/Manage) permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Azure DevOps CLI
      shell: bash
      run: |
        az extension add --name azure-devops --upgrade --yes

    - name: Login to Azure DevOps
      shell: bash
      env:
        AZURE_DEVOPS_PAT: ${{ inputs.pat }}
      run: |
        ORG_URL="https://${{ inputs.organization }}"

        echo "Logging in to Azure DevOps..."
        echo $AZURE_DEVOPS_PAT | az devops login --organization $ORG_URL

    - name: Create Project and Repository if Needed
      shell: bash
      env:
        AZURE_DEVOPS_PAT: ${{ inputs.pat }}
      run: |
        ORG_URL="https://${{ inputs.organization }}"
        PROJECT="${{ github.event.repository.name }}"
        REPO_NAME="${{ github.event.repository.name }}"

        az devops configure --defaults organization=$ORG_URL project=$PROJECT

        if ! az devops project show --project "$PROJECT" >/dev/null 2>&1; then
          echo "🚀 Creating project: $PROJECT"
          az devops project create --name "$PROJECT" --organization $ORG_URL
          echo "✅ Project created: $PROJECT"
        else
          echo "ℹ️ Project $PROJECT already exists"
        fi

        if ! az repos show --repository "$REPO_NAME" >/dev/null 2>&1; then
          echo "🚀 Creating repository: $REPO_NAME"
          az repos create --name "$REPO_NAME"
          echo "✅ Repository created: $REPO_NAME"
        else
          echo "ℹ️ Repository $REPO_NAME already exists"
        fi

    - name: Sync to Azure DevOps
      shell: bash
      env:
        AZURE_DEVOPS_PAT: ${{ inputs.pat }}
      run: |
        ORG_URL="${{ inputs.organization }}"
        PROJECT="${{ github.event.repository.name }}"
        REPO_NAME="${{ github.event.repository.name }}"

        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git remote add azure https://actions:${AZURE_DEVOPS_PAT}@$ORG_URL/$PROJECT/_git/$REPO_NAME || true
        git push azure --all --force
        git push azure --tags --force

        echo "✅ Synced $REPO_NAME to Azure DevOps"
